/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef EVERRUNVMTABLE_H
#define EVERRUNVMTABLE_H

/* function declarations */
void init_everRunVMTable(void);
void initialize_table_everRunVMTable(void);
Netsnmp_Node_Handler everRunVMTable_handler;
Netsnmp_First_Data_Point  everRunVMTable_get_first_data_point;
Netsnmp_Next_Data_Point   everRunVMTable_get_next_data_point;
NetsnmpCacheLoad everRunVMTable_load;
NetsnmpCacheFree everRunVMTable_free;
#define EVERRUNVMTABLE_TIMEOUT  60

/* column number definitions for table everRunVMTable */
       #define COLUMN_EVERRUNVMID		1
       #define COLUMN_EVERRUNVMDISPLAYNAME		2
       #define COLUMN_EVERRUNVMRUNNINGNODE		3
       #define COLUMN_EVERRUNVMAVAILABILITY		4
#endif /* EVERRUNVMTABLE_H */
