/*
 * Note: current file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "everRunVMTable.h"

/** Initializes the everRunVMTable module */
void
init_everRunVMTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_everRunVMTable();
}

  //# Determine the first/last column names

/** Initialize the everRunVMTable table by defining its contents and how it's structured */
void
initialize_table_everRunVMTable(void)
{
    const oid everRunVMTable_oid[] = {1,3,6,1,4,1,458,115,1,17};
    const size_t everRunVMTable_oid_len   = OID_LENGTH(everRunVMTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("everRunVMTable:init", "initializing table everRunVMTable\n"));

    reg = netsnmp_create_handler_registration(
              "everRunVMTable",     everRunVMTable_handler,
              everRunVMTable_oid, everRunVMTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_OCTET_STR,  /* index: everRunVMId */
                           0);
    table_info->min_column = COLUMN_EVERRUNVMID;
    table_info->max_column = COLUMN_EVERRUNVMAVAILABILITY;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = everRunVMTable_get_first_data_point;
    iinfo->get_next_data_point  = everRunVMTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );
    netsnmp_inject_handler_before( reg, 
        netsnmp_get_cache_handler(EVERRUNVMTABLE_TIMEOUT,
                                  everRunVMTable_load, everRunVMTable_free,
                                  everRunVMTable_oid, everRunVMTable_oid_len),
            TABLE_ITERATOR_NAME);

    /* Initialise the contents of the table here */
}

int NNN = 100;
    /* Typical data structure for a row entry */
struct everRunVMTable_entry {
    /* Index values */
    char everRunVMId[100];
    size_t everRunVMId_len;

    /* Column values */
    char everRunVMDisplayName[100];
    size_t everRunVMDisplayName_len;
    char everRunVMRunningNode[100];
    size_t everRunVMRunningNode_len;
    char everRunVMAvailability[100];
    size_t everRunVMAvailability_len;

    struct everRunVMTable_entry *next;
};

struct everRunVMTable_entry  *everRunVMTable_head;

/* create a new row in the (unsorted) table */
struct everRunVMTable_entry *
everRunVMTable_createEntry(
                 char* everRunVMId,
                 size_t everRunVMId_len,
                 char* everRunVMDisplayName,
                 size_t everRunVMDisplayName_len,
                 char* everRunVMRunningNode,
                 size_t everRunVMRunningNode_len,
                 char* everRunVMAvailability,
                 size_t everRunVMAvailability_len
                ) {
    struct everRunVMTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct everRunVMTable_entry);
    if (!entry)
        return NULL;

    memcpy(entry->everRunVMId, everRunVMId, everRunVMId_len);
    entry->everRunVMId_len = everRunVMId_len;

    memcpy(entry->everRunVMDisplayName, everRunVMDisplayName, everRunVMDisplayName_len);
    entry->everRunVMDisplayName_len = everRunVMDisplayName_len;

    memcpy(entry->everRunVMRunningNode, everRunVMRunningNode, everRunVMRunningNode_len);
    entry->everRunVMId_len = everRunVMRunningNode_len;

    memcpy(entry->everRunVMAvailability, everRunVMAvailability, everRunVMAvailability_len);
    entry->everRunVMRunningNode_len = everRunVMAvailability_len;

    entry->next = everRunVMTable_head;
    everRunVMTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
everRunVMTable_removeEntry( struct everRunVMTable_entry *entry ) {
    struct everRunVMTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = everRunVMTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        everRunVMTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

/* Example cache handling - set up linked list from a suitable file */
int
everRunVMTable_load( netsnmp_cache *cache, void *vmagic ) {
    FILE *fp;
    struct everRunVMTable_entry *current;
    char buf[1000];
    fp = fopen( "/usr/everRunVMTable", "r" );
    if ( !fp ) {
        return -1;
    }
    while ( fgets( buf, 1000, fp )) {
        current = SNMP_MALLOC_TYPEDEF( struct everRunVMTable_entry );

        sprintf(current->everRunVMId, "%s", buf);
        current->everRunVMId_len = strlen(current->everRunVMId);
        current->next = everRunVMTable_head;
        everRunVMTable_head = current;    /* Iterate helper is fine with unordered lists! */
    }
    fclose(fp);
    return 0;  /* OK */
}

void
everRunVMTable_free( netsnmp_cache *cache, void *vmagic ) {
    struct everRunVMTable_entry *current, *that;

    for ( current = everRunVMTable_head; current; current=that ) {
        that = current->next;
        SNMP_FREE( current );   /* XXX - release any other internal resources */
    }
    everRunVMTable_head = NULL;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
everRunVMTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = everRunVMTable_head;
    return everRunVMTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
everRunVMTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct everRunVMTable_entry *entry = (struct everRunVMTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_value( idx, entry->everRunVMId, sizeof(entry->everRunVMId) );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the everRunVMTable table */
int
everRunVMTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct everRunVMTable_entry          *table_entry;

    DEBUGMSGTL(("everRunVMTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct everRunVMTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_EVERRUNVMID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->everRunVMId,
                                          table_entry->everRunVMId_len);
                break;
            case COLUMN_EVERRUNVMDISPLAYNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->everRunVMDisplayName,
                                          table_entry->everRunVMDisplayName_len);
                break;
            case COLUMN_EVERRUNVMRUNNINGNODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->everRunVMRunningNode,
                                          table_entry->everRunVMRunningNode_len);
                break;
            case COLUMN_EVERRUNVMAVAILABILITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->everRunVMAvailability,
                                          table_entry->everRunVMAvailability_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
